name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.malekekhemiri}} -p ${{ secrets.Maleke2023@ }}

    - name: Build and push Docker image
      run: |
        docker build -t imgexample:1.0 .
        docker tag myapp:latest ${{ secrets.malekekhemiri }}/imgexample:1.0
        docker push ${{ secrets.malekekhemiri}}/imgexample:1.0
      env:
     DOCKER_CLI_ASK_PASS: 1

